---
title: "Weather file decomposition"
author: "Mike Wood"
date: "24 November 2016"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
    toc: no
  html_document:
    toc: no
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Testing building is a complicated process. One of the main things that you need to do is test for overheating. However, since differnet types of buildings overheat differently and we don't know what type of weather events a building might experience, we have a problem. How big should the overheating events be? What constitutes 'bigness'? Should we test buildings the same way in Newcastle as we test them in London. And how do we define a local climate? Climates are changing all the time, so you cannot know for certain what the climate might be like in a given location - let alone guess what the individual overheating events might be. 

There are a lot of questions to answer - and there are equally as many ways to answer them. HOwever, we need to start somewhere. In this paper, we have decided to look at the very bottom of the question tree... How do we define a heatwave? 

Clearly temperatures indoors differ from outdoors (otherwise why would we be worried about buildings?). But even if we just want to find a clear definition of what an *outdoor* heatwave is, we find ourselves struggling. There are many different definitions:

- various definition of heatwaves from Ed's paper <!-- Add the definitions here -->

We have also recently shown that it is **very** difficult to assess whether a building is overheating internally, since, again there are so many different overheating measurement methods to choose from. Eames has looking into this in his recent paper for the *Winsor Conference*. Among other things, the paper looks at extreme internal overheating events. He looked for heatwaves with severities that occured every 1:7 years and every 1:21 years. However, instead of rating the severity by the *external* temperature, he rated them using the *internal* temperature. The results were interesting.

Eames chose years that had a 1:7 year event in them, based on the internal overheating metric. However, the year chosen was dependent on the overheating metric chosen. In other words, the overheating metric you choose will affect how 'severe' a heat wave appears. 

In some ways this is to be expected because different overheating metrics measure different things. 

What we need is a good method for finding overheating events that trigger a particular metric. This would solve two problems:

- It would enable 'redundant' sections of the weather file to be removed, thereby reducing the computational burden in testing buildings for overheating. 
- If we know how much an overheating event will trigger a particular metric, then we can analyse past and future weather to identify how often a particular event is likely to occur. We can then use weather generation models (such as the UKCP09 weather generator) to make predictions of how many of these events are likely to occur in the future. 

Once we have this information, we might have better tools for 'stress testing' buidlings designs for the events that they might encounter in the future. However, we first need some tools to identify these events so that this research can begin. 

Our work is in three stages:

- identify the overheating criteria (as this will affect the overheating events selected - as we have already seen)
- find out when this overheating criteria is likely to be triggered in a given weather file
- rate the overheating events in each weather file according to their severity

## Aims

The aim of this work is to develop a method for linking and *overheating criteria* to *events* and to be able to *rate their severtiy*. 

# Method

We use the criteria in CIBSE TM 52 [@TM52] as our basis for measuring overheating. 

Here's how we did it:







